### ISSUE TITLE
Daily snapshot, generated 2019-12-29

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/scripts#22]
Is snapshot generation stuck in 2019? ;)

Perhaps 5.0 could be listed before 4.9 @ https://www.phpmyadmin.net/downloads/

**Comment by ibennetch** [comment]
That's because the tests are failing, which the script feels means it shouldn't generate a new build (preferring a working but older build over a new but potentially broken build).

Why the tests are suddenly failing is strange, though. It's the EnvironmentTest::testMySQL test and it can't connect to the MySQL instance. Nothing should have changed here for some time, so why is it suddenly failing?

Thanks for the report, I'll look in to this.

**Comment by ibennetch** [comment]
As far as 5.0 being listed first, I agree.

I've opened https://github.com/phpmyadmin/website/issues/97 to track this.

**Comment by ibennetch** [comment]
Daily downloads should be up to date once again, thanks for the report.

**Comment by OlafvdSpek** [comment]
Why were the tests failing?
Is there a notification when snapshot generation is failing?

**Comment by ibennetch** [comment]
> Why were the tests failing?

There error on the testsuite was that it couldn't connect to the MySQL server, which was quite odd because when I checked on it, it was working fine. It seems like some odd one-time issue because I don't ever remember seeing that particular error before. 

> Is there a notification when snapshot generation is failing?

Sort of. There is a script that checks for recent snapshots, but it was more fragile than I liked. Notifications currently go to the infrastructure team. I actually spent some time working on monitoring scripts this week and am rolling out improvements to not only this but also checking on the Docker and Composer downloads.

**Comment by ibennetch** [comment]
See also #23, I'm working on integrating these in to the phpMyAdmin infrastructure instead of my own local machine.

**Comment by williamdes** [comment]
@ibennetch having the scripts in the git repo will help all of us understand more of the infrastructure and help improve it ;)

**Comment by OlafvdSpek** [comment]
2020-01-10: Daily snapshot, generated 2020-01-07, from Git commit 2e2c20ac319fe1b0039f18409c30b70998cc44d1.

**Comment by williamdes** [comment]
Strange, I fixed tests yesterday

**Comment by ibennetch** [comment]
I'm seeing this: Daily snapshot, generated 2020-01-10, from Git commit 6650498f2eb413f848fe770d56a5ace838849626.

Probably it rebuilt the image in the 12 hours between when you reported this and when I checked it, but maybe there had been some caching issue with our CDN.

I have increased the logging of the build script to see if I can get some more details about what's going on recently.

**Comment by williamdes** [comment]
> Why the tests are suddenly failing is strange, though. It's the EnvironmentTest::testMySQL test and it can't connect to the MySQL instance. Nothing should have changed here for some time, so why is it suddenly failing?

I found out:
before the MariaDB upgrade localhost was localhost
now localhost converts to a socket and 127.0.0.1 needs to be used.

Fixed by: https://github.com/phpmyadmin/phpmyadmin/commit/fb134b0380dbbb9b8af91873906483146a7ab730
